name: e_movies
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^2.1.0
  http: ^0.12.0+4
  provider: ^4.0.4
  cached_network_image: ^2.0.0
  intl: ^0.16.1
  rating_bar: ^0.2.0  
  transparent_image: ^1.0.0 
  flutter_spinkit: "^4.1.2"   
  # video_player: ^0.10.8+1
  # video_player: ^0.10.9+1
  # chewie: ^0.9.10
  hexcolor: ^1.0.1
  youtube_player_flutter: ^6.1.0+7 
  flutter_svg: ^0.17.4
  video_player: ^0.10.9+1
  photo_view: ^0.9.2
  shared_preferences: ^0.5.7+2
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:    
    - .env
    
    - assets/images/background_image_1.jpg
    - assets/images/movie_list_image.jpg
    - assets/images/logo.png
    - assets/images/poster_placeholder.png        
    - assets/images/placeholder.png   
    - assets/icons/play.svg
    - assets/icons/play.gif

    - assets/images/movies/action.jpg
    - assets/images/movies/adventure.jpg
    - assets/images/movies/comedy.jpg
    - assets/images/movies/animation.jpg
    - assets/images/movies/comedy.jpg
    - assets/images/movies/crime.jpeg
    - assets/images/movies/documentary.jpg
    - assets/images/movies/drama.jpg
    - assets/images/movies/family.jpg
    - assets/images/movies/fantasy.jpg
    - assets/images/movies/history.jpg
    - assets/images/movies/horror.jpg
    - assets/images/movies/music.jpg
    - assets/images/movies/mystery.jpg
    - assets/images/movies/romance.jpg
    - assets/images/movies/sci-fi.jpg
    - assets/images/movies/thriller.jpg
    - assets/images/movies/war.jpg
    - assets/images/movies/western.jpg

    - assets/images/tv/action_adventure.jpg    
    - assets/images/tv/comedy.jpg
    - assets/images/tv/animation.jpg
    - assets/images/tv/comedy.jpg
    - assets/images/tv/crime.jpg    
    - assets/images/tv/drama.jpg
    - assets/images/tv/documentary.jpg
    - assets/images/tv/family.jpg
    - assets/images/tv/kids.jpg    
    - assets/images/tv/mystery.jpg
    - assets/images/tv/news.jpg
    - assets/images/tv/reality.jpg
    - assets/images/tv/sci-fi_fantasy.jpg
    - assets/images/tv/sci-fi.jpg
    - assets/images/tv/soap.jpg
    - assets/images/tv/talk.jpg
    - assets/images/tv/western.jpg
    - assets/images/tv/war_politics.jpg
        
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Helvatica
      fonts:
        - asset: assets/fonts/helvatica/Helvetica.ttf
        # - asset: assets/fonts/Roboto-Medium.ttf 

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto-Medium.ttf 

    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/roboto_condensed/RobotoCondensed-Regular.ttf          
        # - asset: assets/fonts/Roboto-Medium.ttf          
    - family: OpenSans
      fonts:
        - asset: assets/fonts/Open_Sans/OpenSans-Regular.ttf
        # - asset: assets/fonts/Roboto-Medium.ttf          
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
